-- =====================================================================
--  AMBANGAN FAST PRINT  -  Oracle schema + seed data (consolidated)
--  Source: "Create Table AMBANGANFASTPRINT SCHEMA.txt"
--        + "INHERITANCEAMBANGANFASTPRINT.txt"
--  Target: Oracle XE 21c (gvenzl/oracle-xe), schema AMBANGANFASTPRINT
--
--  Notes:
--   * SET DEFINE OFF  -> stops SQL*Plus treating '&' (e.g. 'Banner&Bunting')
--     as a substitution variable, which would otherwise prompt / hang.
--   * Drop block up top makes the script safely re-runnable.
--   * Circular FK (ORDERS<->RECEIPT) is added AFTER both tables exist.
--   * Inheritance/subtype rows are inserted after SERVICE is populated.
-- =====================================================================

SET DEFINE OFF;
WHENEVER SQLERROR CONTINUE;

-- ---------- clean slate (ignore "table does not exist") ----------
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'DELIVERY','ORDERSERVICE','RECEIPT','ORDERS','MACHINE',
      'BANNERANDBUNTING','NAMETAG','RUBBERSTAMP','BUSINESSCARD','PRINT',
      'SERVICE','EMPLOYEE','CUSTOMER')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- =====================================================================
--  TABLES
-- =====================================================================

--CUSTOMER
create table CUSTOMER(
    CustomerID number generated by default as identity (start with 1 increment by 1),
    CustomerName varchar2(100) not null,
    CustomerPhoneNum varchar2(20),
    CustomerEmail varchar2(120),                 -- added: website identifies customers by email
    constraint Customer_CustomerID_PK primary key (CustomerID)
);

--EMPLOYEE
create table EMPLOYEE(
    EmployeeID number generated by default as identity (start with 1 increment by 1),
    EmployeeName varchar2(100) not null,
    EmployeePhone varchar2(20),
    EmployeeJobPosition varchar2(50),
    constraint Employee_EmployeeID_PK primary key (EmployeeID)
);

--SERVICE
create table SERVICE(
    ServiceID number generated by default as identity (start with 51 increment by 1),
    ServiceType varchar2(100) not null,
    ServicePrice number(10,2) check(ServicePrice>0),
    ServiceDesignPicture varchar2(255),
    constraint Service_ServiceID_PK primary key (ServiceID)
);

-- PRINT
CREATE TABLE PRINT(
    ServiceID NUMBER,
    PDocumentName VARCHAR2(100),
    PSelectedPage NUMBER,
    PaperType VARCHAR2(50),
    PColourType VARCHAR2(50),
    CONSTRAINT Print_ServiceID_PK PRIMARY KEY (ServiceID),
    CONSTRAINT Print_ServiceID_FK FOREIGN KEY (ServiceID)
        REFERENCES SERVICE(ServiceID)
);

-- BUSINESSCARD
CREATE TABLE BUSINESSCARD(
    ServiceID NUMBER,
    BSDoubleSided VARCHAR2(5) CHECK (BSDoubleSided IN ('Yes','No')),
    BSCardThickness NUMBER(10,2) CHECK (BSCardThickness IN (0.35, 0.40, 0.80)),
    BSCornerStyle VARCHAR2(50) CHECK (BSCornerStyle IN ('Round','Square')),
    CONSTRAINT BusinessCard_ServiceID_PK PRIMARY KEY (ServiceID),
    CONSTRAINT BusinessCard_ServiceID_FK FOREIGN KEY (ServiceID)
        REFERENCES SERVICE(ServiceID)
);

-- RUBBERSTAMP
CREATE TABLE RUBBERSTAMP(
    ServiceID NUMBER,
    RSStampType VARCHAR2(50) CHECK (RSStampType IN ('Self-Inking','Pre-Inked','Traditional','Company Stamp')),
    RSKeychain VARCHAR2(5),
    RSInkColour VARCHAR2(50),
    RSCover VARCHAR2(50),
    RSTextAlignment VARCHAR2(50),
    CONSTRAINT RubberStamp_ServiceID_PK PRIMARY KEY (ServiceID),
    CONSTRAINT RubberStamp_ServiceID_FK FOREIGN KEY (ServiceID)
        REFERENCES SERVICE(ServiceID)
);

-- NAMETAG
CREATE TABLE NAMETAG(
    ServiceID NUMBER,
    NTMaterial VARCHAR2(50),
    NTLogo VARCHAR2(255),
    NTColor VARCHAR2(50),
    NTAttachmentType VARCHAR2(50),
    CONSTRAINT NameTag_ServiceID_PK PRIMARY KEY (ServiceID),
    CONSTRAINT NameTag_ServiceID_FK FOREIGN KEY (ServiceID)
        REFERENCES SERVICE(ServiceID)
);

-- BANNERANDBUNTING
CREATE TABLE BANNERANDBUNTING(
    ServiceID NUMBER,
    PickOrientation VARCHAR2(50) CHECK (PickOrientation IN ('Horizontal','Vertical')),
    CONSTRAINT BannerAndBunting_ServiceID_PK PRIMARY KEY (ServiceID),
    CONSTRAINT BannerAndBunting_ServiceID_FK FOREIGN KEY (ServiceID)
        REFERENCES SERVICE(ServiceID)
);

--MACHINE
create table MACHINE(
    MachineID number generated by default as identity (start with 34 increment by 1),
    MachineName varchar2(100) not null,
    MachineType varchar2(80) not null,
    MachineBrand varchar2(80) not null,
    MachineStatus varchar2(30) CHECK(MachineStatus in('Active','Maintenance')),
    constraint Machine_MachineID_PK primary key (MachineID)
);

--ORDERS
create table ORDERS(
    OrderID number generated by default as identity (start with 1 increment by 1),
    OrderDateTime date not null,
    EmployeeID number not null,
    ReceiptID number,
    CustomerID number not null,
    Remark varchar2(255),
    OrderStatus varchar2(20) default 'Pending'   -- added: dashboard order lifecycle
        check (OrderStatus in ('Pending','Ready to Pick Up','Completed','Cancelled')),
    constraint Orders_OrderID_PK primary key (OrderID),
    constraint Orders_EmployeeID_FK foreign key (EmployeeID) references EMPLOYEE(EmployeeID),
    constraint Orders_CustomerID_FK foreign key (CustomerID) references CUSTOMER(CustomerID)
);

--ORDERSERVICE
create table ORDERSERVICE(
    ServiceID number not null,
    OrderID number not null,
    Quantity number check(quantity>0),
    OSSize varchar2(50),
    Text varchar2(500),
    AmountPrice number(10,2),
    MachineID number,
    constraint OrderService_PK primary key (ServiceID, OrderID),
    constraint OrderService_ServiceID_FK foreign key (ServiceID) references SERVICE(ServiceID),
    constraint OrderService_OrderID_FK foreign key (OrderID) references ORDERS(OrderID),
    constraint OrderService_MachineID_FK foreign key (MachineID) references MACHINE(MachineID)
);

--RECEIPT
create table RECEIPT(
    ReceiptID number generated by default as identity (start with 1 increment by 1),
    ReceiptDate date DEFAULT SYSDATE,
    PaymentMethod varchar2(50) not null CHECK (PaymentMethod IN ('Cash','Card','Online')),
    EmployeeID number not null,
    OrderID number,
    ReceiptDepoAmount number(10,2),
    ReceiptTotalAmount number(10,2) check (ReceiptTotalAmount>0),
    constraint Receipt_ReceiptID_PK primary key (ReceiptID),
    constraint Receipt_EmployeeID_FK foreign key (EmployeeID) references EMPLOYEE(EmployeeID)
);

--DELIVERY
create table DELIVERY(
    DeliveryID number generated by default as identity (start with 1 increment by 1),
    DeliveryDate date default sysdate,
    DeliveryAddress varchar2(255) not null,
    DeliveryRemark varchar2(255),
    OrderID number unique,
    TrackingNumber varchar2(100),
    constraint Delivery_DeliveryID_PK primary key (DeliveryID),
    constraint Delivery_OrderID_FK foreign key (OrderID) references ORDERS(OrderID)
);

--CIRCULAR FOREIGN KEYS
alter table ORDERS
add constraint Orders_ReceiptID_FK
foreign key (ReceiptID)
references RECEIPT(ReceiptID);

alter table RECEIPT
add constraint Receipt_OrderID_FK
foreign key (OrderID)
references ORDERS(OrderID);

-- =====================================================================
--  SEED DATA
-- =====================================================================

INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Ali Ahmad', '012-1000001');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Siti Aisyah', '012-1000002');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('John Tan', '012-1000003');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Raj Kumar', '012-1000004');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Nur Amalina', '012-1000005');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Lim Wei', '012-1000006');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Farah Zain', '012-1000007');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Aiman Hakim', '012-1000008');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Mei Ling', '012-1000009');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('David Lee', '012-1000010');
INSERT INTO CUSTOMER (CustomerName, CustomerPhoneNum) VALUES ('Hafiz Rahman', '012-1000011');

INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Zul', '013-2000001', 'Manager');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Hana', '013-2000002', 'Cashier');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Arif', '013-2000003', 'Designer');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Kumar', '013-2000004', 'Operator');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Sofia', '013-2000005', 'Sales');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Jason', '013-2000006', 'Technician');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Nadia', '013-2000007', 'Admin');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Hakim', '013-2000008', 'Printer');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Lina', '013-2000009', 'Designer');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Amir', '013-2000010', 'Operator');
INSERT INTO EMPLOYEE (EmployeeName, EmployeePhone, EmployeeJobPosition) VALUES ('Rina', '013-2000011', 'Sales');

INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Canon A1', 'Printer', 'Canon', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Epson B1', 'Printer', 'Epson', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('HP Cutter', 'Rubber Stamp', 'HP', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Roland UV', 'Printer', 'Roland', 'Maintenance');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Brother P1', 'Sticker', 'Brother', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Laminator X', 'Laminator', 'Fellowes', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Zebra Label', 'Name Tag', 'Zebra', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Heat Press', 'Press', 'Stahls', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Vinyl Cutter', 'Cutter', 'Silhouette', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('Laser Engraver', 'Engraver bussiness Card', 'Glowforge', 'Active');
INSERT INTO MACHINE (MachineName, MachineType, MachineBrand, MachineStatus) VALUES ('UV Printer X', 'Banner&Bunting', 'Mimaki', 'Active');

INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('P', 0.30, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('BC', 20.25,NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice,ServiceDesignPicture) VALUES ('RS', 12.30, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('NT', 10.00, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('B', 97.00, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('Flyer', 5.00, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('Sticker', 12.30, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('BC', 17.40, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('RS', 14.30, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('Poster', 8.00, NULL);
INSERT INTO SERVICE (ServiceType, ServicePrice, ServiceDesignPicture) VALUES ('P', 0.60, NULL);

INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('14-JUN-2026 10:15:10 AM', 'DD-MON-YYYY HH:MI:SS AM'), 1, NULL, 1, 'Urgent');
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('13-JUN-2026 02:30:45 PM', 'DD-MON-YYYY HH:MI:SS AM'), 2, NULL, 2, NULL);
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('12-JUN-2026 09:05:20 AM', 'DD-MON-YYYY HH:MI:SS AM'), 3, NULL, 3, 'Express');
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('11-JUN-2026 11:45:55 AM', 'DD-MON-YYYY HH:MI:SS AM'), 4, NULL, 4, 'take next week 25/7/2026');
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('10-JUN-2026 03:20:10 PM', 'DD-MON-YYYY HH:MI:SS AM'),  5, NULL, 5, NULL);
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('09-JUN-2026 08:10:33 AM', 'DD-MON-YYYY HH:MI:SS AM'), 6, NULL, 6, NULL);
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('08-JUN-2026 01:55:40 PM', 'DD-MON-YYYY HH:MI:SS AM'), 7, NULL, 7, 'Urgent');
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('07-JUN-2026 06:25:15 PM', 'DD-MON-YYYY HH:MI:SS AM'), 8, NULL, 8, NULL);
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('06-JUN-2026 07:40:50 AM', 'DD-MON-YYYY HH:MI:SS AM'),9, NULL, 9, 'take next week 25/7/2026');
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('05-JUN-2026 12:05:25 PM', 'DD-MON-YYYY HH:MI:SS AM'), 10, NULL, 10, NULL);
INSERT INTO ORDERS (OrderDateTime, EmployeeID, ReceiptID, CustomerID, Remark)
VALUES (TO_DATE('04-JUN-2026 04:50:00 PM', 'DD-MON-YYYY HH:MI:SS AM'), 11, NULL, 11, 'Express');

INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('14-JUN-2026 10:15:10 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Cash', 1, 1, null, 0.90);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('13-JUN-2026 02:30:45 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Card', 2, 2, null, 81.00);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('12-JUN-2026 09:05:20 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Cash', 3, 3, 32.00, 62.70);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('11-JUN-2026 11:45:55 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Online', 4, 4, 10.99, 80);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('10-JUN-2026 03:20:10 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Cash', 5, 5, 6.45, 25.80);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('09-JUN-2026 08:10:33 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Card', 6, 6, 7.30, 35.20);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('08-JUN-2026 01:55:40 PM', 'DD-MON-YYYY HH:MI:SS AM'),'Cash', 7, 7, 9.15, 45.90);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('07-JUN-2026 06:25:15 PM', 'DD-MON-YYYY HH:MI:SS AM'),'Online', 8, 8, 10.00, 55.50);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('06-JUN-2026 07:40:50 AM', 'DD-MON-YYYY HH:MI:SS AM'),'Cash', 9, 9, 5.60, 20.75);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('05-JUN-2026 12:05:25 PM', 'DD-MON-YYYY HH:MI:SS AM'),'Card', 10, 10, 12.40, 70.99);
INSERT INTO RECEIPT (ReceiptDate, PaymentMethod, EmployeeID, OrderID, ReceiptDepoAmount, ReceiptTotalAmount)
VALUES (TO_DATE('04-JUN-2026 04:50:00 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Cash', 11, 11, 15.00, 80.00);

UPDATE ORDERS SET ReceiptID = 1 WHERE OrderID = 1;
UPDATE ORDERS SET ReceiptID = 2 WHERE OrderID = 2;
UPDATE ORDERS SET ReceiptID = 3 WHERE OrderID = 3;
UPDATE ORDERS SET ReceiptID = 4 WHERE OrderID = 4;
UPDATE ORDERS SET ReceiptID = 5 WHERE OrderID = 5;
UPDATE ORDERS SET ReceiptID = 6 WHERE OrderID = 6;
UPDATE ORDERS SET ReceiptID = 7 WHERE OrderID = 7;
UPDATE ORDERS SET ReceiptID = 8 WHERE OrderID = 8;
UPDATE ORDERS SET ReceiptID = 9 WHERE OrderID = 9;
UPDATE ORDERS SET ReceiptID = 10 WHERE OrderID = 10;
UPDATE ORDERS SET ReceiptID = 11 WHERE OrderID = 11;

INSERT INTO ORDERSERVICE VALUES (51, 1, 3, 'A4', null, 0.90, 44);
INSERT INTO ORDERSERVICE VALUES (52, 2, 4, '2.5 x 2.165', 'Siti Bussienss Card', 81.00, 43);
INSERT INTO ORDERSERVICE VALUES (53, 3, 5, 'Small', 'CUSTOM STAMP: ABC Trading', 61.50, 36);
INSERT INTO ORDERSERVICE VALUES (54, 4, 3, 'Medium', 'NAME TAG: Ahmad', 80.00, 40);
INSERT INTO ORDERSERVICE VALUES (55, 5, 3, 'Large', 'Banner: Grand Opening Sale', 346, 44);
INSERT INTO ORDERSERVICE VALUES (56, 6, 2, NULL, 'Flyer Design: Promo Week', 10.00, 35);
INSERT INTO ORDERSERVICE VALUES (57, 7, 3, 'Round', 'Sticker: Logo XYZ',36.90 , 38);
INSERT INTO ORDERSERVICE VALUES (58, 8, 2, '3.5 x 2', 'Bussiness Card', 34.80, 39);
INSERT INTO ORDERSERVICE VALUES (59, 9, 3, 'Rectangle', 'STAMP: Company Seal',42.90 , 36);
INSERT INTO ORDERSERVICE VALUES (60, 10, 4, 'A3', 'Poster: Event Launch', 12.00, 44);
INSERT INTO ORDERSERVICE VALUES (61, 11, 2, 'A3', 'Cut a4 paper',12.00 , 42);
INSERT INTO ORDERSERVICE VALUES (51, 5, 3, 'A4', null, 0.90, 34);
INSERT INTO ORDERSERVICE VALUES (51, 3, 4, 'A3', null,1.20 , 35);
INSERT INTO ORDERSERVICE VALUES (56, 1, 2, NULL, 'Flyer Design', 10.00, 35);
INSERT INTO ORDERSERVICE VALUES (57, 1, 3, 'Round', 'Sticker Logo', 36.90, 38);
INSERT INTO ORDERSERVICE VALUES (60, 2, 1, 'A3', 'Poster Printing', 8.00, 44);
INSERT INTO ORDERSERVICE VALUES (58, 4, 2, '3.5 x 2', 'Business Card', 34.80, 39);
INSERT INTO ORDERSERVICE VALUES (61, 6, 2, 'A4', 'Extra Printing', 1.20, 42);
INSERT INTO ORDERSERVICE VALUES (54, 7, 1, 'Medium', 'Name Tag Extra', 10.00, 40);

INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('13-JUN-2026 02:40:25 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'PJ', 'Normal', 2, 'TRK002');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('12-JUN-2026 11:05:55 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Shah Alam', 'Urgent', 3, 'TRK003');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('11-JUN-2026 03:30:40 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Subang', 'VIP', 4, 'TRK004');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('10-JUN-2026 08:10:15 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Klang', 'Normal', 5, 'TRK005');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('08-JUN-2026 10:20:35 AM', 'DD-MON-YYYY HH:MI:SS AM'), 'Kajang', 'Urgent', 7, 'TRK007');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('07-JUN-2026 04:45:20 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Ampang', 'Normal', 8, 'TRK008');
INSERT INTO DELIVERY (DeliveryDate, DeliveryAddress, DeliveryRemark, OrderID, TrackingNumber)
VALUES (TO_DATE('05-JUN-2026 12:35:45 PM', 'DD-MON-YYYY HH:MI:SS AM'), 'Cheras', 'Express', 10, 'TRK010');

-- =====================================================================
--  INHERITANCE / SUBTYPE DATA  (ServiceID must already exist in SERVICE)
-- =====================================================================

-- PRINT (ServiceID, PDocumentName, PSelectedPage, PaperType, PColourType)
INSERT INTO PRINT VALUES (51, 'Doc A', 10, 'A4', 'B/W');
INSERT INTO PRINT VALUES (56, 'Flyer File', 5, 'A5', 'Colour');
INSERT INTO PRINT VALUES (61, 'Color Print File', 8, 'A3', 'Full Colour');

-- BUSINESSCARD (ServiceID, BSDoubleSided, BSCardThickness, BSCornerStyle)
INSERT INTO BUSINESSCARD VALUES (52, 'Yes', 0.35, 'Round');
INSERT INTO BUSINESSCARD VALUES (58, 'No', 0.40, 'Square');

-- RUBBERSTAMP (ServiceID, RSStampType, RSKeychain, RSInkColour, RSCover, RSTextAlignment)
INSERT INTO RUBBERSTAMP VALUES (53, 'Self-Inking', 'No', 'Black', 'Plastic', 'Center');
INSERT INTO RUBBERSTAMP VALUES (59, 'Traditional', 'Yes', 'Blue', 'Metal', 'Left');

-- NAMETAG (ServiceID, NTMaterial, NTLogo, NTColor, NTAttachmentType)
INSERT INTO NAMETAG VALUES (54, 'Plastic', 'Logo A', 'Blue', 'Clip');

-- BANNERANDBUNTING (ServiceID, PickOrientation)
INSERT INTO BANNERANDBUNTING VALUES (55, 'Horizontal');
INSERT INTO BANNERANDBUNTING VALUES (60, 'Vertical');

-- ---------------------------------------------------------------------
--  ALIGNMENT FILL  (new columns added for the website)
-- ---------------------------------------------------------------------
-- Customer emails (website looks up accounts/orders by email)
UPDATE CUSTOMER SET CustomerEmail = 'ali.ahmad@gmail.com'      WHERE CustomerID = 1;
UPDATE CUSTOMER SET CustomerEmail = 'siti.aisyah@moe.gov.my'   WHERE CustomerID = 2;
UPDATE CUSTOMER SET CustomerEmail = 'john.tan@gmail.com'       WHERE CustomerID = 3;
UPDATE CUSTOMER SET CustomerEmail = 'raj.kumar@email.com'      WHERE CustomerID = 4;
UPDATE CUSTOMER SET CustomerEmail = 'nur.amalina@moe.gov.my'   WHERE CustomerID = 5;
UPDATE CUSTOMER SET CustomerEmail = 'lim.wei@gmail.com'        WHERE CustomerID = 6;
UPDATE CUSTOMER SET CustomerEmail = 'farah.zain@email.com'     WHERE CustomerID = 7;
UPDATE CUSTOMER SET CustomerEmail = 'aiman.hakim@gmail.com'    WHERE CustomerID = 8;
UPDATE CUSTOMER SET CustomerEmail = 'mei.ling@email.com'       WHERE CustomerID = 9;
UPDATE CUSTOMER SET CustomerEmail = 'david.lee@gmail.com'      WHERE CustomerID = 10;
UPDATE CUSTOMER SET CustomerEmail = 'hafiz.rahman@moe.gov.my'  WHERE CustomerID = 11;

-- Order lifecycle status (drives the staff/owner dashboard)
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 1;
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 2;
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 3;
UPDATE ORDERS SET OrderStatus = 'Ready to Pick Up'  WHERE OrderID = 4;
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 5;
UPDATE ORDERS SET OrderStatus = 'Pending'           WHERE OrderID = 6;
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 7;
UPDATE ORDERS SET OrderStatus = 'Ready to Pick Up'  WHERE OrderID = 8;
UPDATE ORDERS SET OrderStatus = 'Pending'           WHERE OrderID = 9;
UPDATE ORDERS SET OrderStatus = 'Completed'         WHERE OrderID = 10;
UPDATE ORDERS SET OrderStatus = 'Cancelled'         WHERE OrderID = 11;

COMMIT;

-- =====================================================================
--  QUICK VERIFICATION
-- =====================================================================
SET LINESIZE 200
SET PAGESIZE 100
COLUMN table_name FORMAT A20
SELECT 'CUSTOMER'          AS table_name, COUNT(*) AS rows_loaded FROM CUSTOMER
UNION ALL SELECT 'EMPLOYEE',         COUNT(*) FROM EMPLOYEE
UNION ALL SELECT 'SERVICE',          COUNT(*) FROM SERVICE
UNION ALL SELECT 'MACHINE',          COUNT(*) FROM MACHINE
UNION ALL SELECT 'ORDERS',           COUNT(*) FROM ORDERS
UNION ALL SELECT 'ORDERSERVICE',     COUNT(*) FROM ORDERSERVICE
UNION ALL SELECT 'RECEIPT',          COUNT(*) FROM RECEIPT
UNION ALL SELECT 'DELIVERY',         COUNT(*) FROM DELIVERY
UNION ALL SELECT 'PRINT',            COUNT(*) FROM PRINT
UNION ALL SELECT 'BUSINESSCARD',     COUNT(*) FROM BUSINESSCARD
UNION ALL SELECT 'RUBBERSTAMP',      COUNT(*) FROM RUBBERSTAMP
UNION ALL SELECT 'NAMETAG',          COUNT(*) FROM NAMETAG
UNION ALL SELECT 'BANNERANDBUNTING', COUNT(*) FROM BANNERANDBUNTING
ORDER BY 1;

PROMPT
PROMPT ====== AMBANGAN FAST PRINT schema build complete ======
